OpenFurther Reference Documentation
===================================

About
-----
The following documentation applies to *OpenFurther version 1.4.0-SNAPSHOT*

Conventions
~~~~~~~~~~~

NOTE: A note

IMPORTANT: An important point

TIP: A tip

WARNING: A warning

CAUTION: A point of caution

Introduction
------------
FURTHeR, The Federated Utah Research and Translational Health electronic Repository, has been developed as part of the Biomedical Informatics Core (BMIC) at the University of Utah’s Center for Clinical and Translational Science (CCTS). FURTHeR’s primary function is to federate health information from heterogeneous data sources to aid researchers in cohort selection and retrospective comparative effectiveness research. FURTHeR achieves real-time federation of health information from heterogeneous data sources using a logical federated query language, a query and result translator for translating queries and results from each heterogeneous data source, and standard terminology to unify data across sources.
